services:
  - type: web
    name: ai-health-assistant-nepal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0

